terminatorInterface.py
adding three tabs: export results, help and log out.
=> modification in the interface

terminatorInterface.py
Reverts wellinkstein/Terminator#13
=> Revert "Modification of the interface"

terminatorInterface.py
J'ai supprimé Log Out et Undo à la vitesse de lumière.
=> Changement dans l'interface

Import_script.py
Changed the value of the export script
=> Export to excel sheet

terminatorInterface.py
Correction pour pouvoir enregistrer document avec le nouveau bouton next de l'onglet execute.
=> correction next save

terminatorInterface.py
Remplacement de Y-M-D par Y-M-D-Hour-Minutes-Seconds pour pouvoir
avoir différents résultats le même jour.
=> Modification nom fichier

terminatorInterface.py
Reverts wellinkstein/Terminator#21
=> Revert "Add files via upload"

terminatorInterface.py
=> on fait rien

MyTable.py, terminatorInterface.py
=> Les triades apparaissent qd on clique sur Next

terminatorInterface.py
Utile pour faire des tests, on est pas obligé de le garder pour le rendu final mais je pense que ça peut être bien.
=> Ajout d'un bouton Previous dans l'onglet Execute

terminatorInterface.py
Quand on ajoute une nouvelle triade dans le tableau grâce à Add Triad, une checkbox est disponible dans la colonne Validated
=> Amélioration de l'ajout de triade

MyTable.py, terminatorInterface.py
=> Le bouton Delete triad fonctionne mtn

MyTable.py, fonctions_terminator.py, terminatorInterface.py
Changement de la majorité du code dans MyTable.py car les listes déroulantes (comboboxes) sont considérées comme des widgets et non comme des items. Fonctionne mais une partie du code de la fonction setValue1 doit être modifiée.
=> Ajout de listes déroulantes

terminatorInterface.py
J'ai ajouté une petite explication du program dans la page "help"
=> modification de la page : "help"

MyTable.py, terminatorInterface.py
=> On doit sélectionner les lignes pour les supprimer

terminatorInterface.py
=> Suppression de l'onglet : "Export result"

Import_script.py, terminatorInterface.py
Modifs pour le beug d'export.
Pour le bouton next, ça marche pas car j'arrive pas a envoyer l'objet du bouton vers le fichier "MyTable" où il y a le checkbox
=> excel et bouton next

terminatorInterface.py
L'import des fichiers (.txt) dans l'interface
=> terminatorInterface

terminatorInterface.py
L'import marche parfaitement, j'ai également testé les résultats obtenues.
=> Correction du problème dans "Import file"

terminatorInterface.py
J'ai ajouté/lié la fonction "add_item" qui existait déjà dans "import_file" en plus de quelques modifs mais elle ne fonctionne pas vraiment
=> Test de la tab "schema"
